name: daily-cron

on:
  schedule:
    # 화요일~토요일 0시
    - cron: 30 15 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run daily.py
      run: |
        python daily.py
      env:
        token: ${{ secrets.token }}
